---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: github
  namespace: flux-system
spec:
  address: https://github.com/delivery-k8s-maksystem/flux-infra
  secretRef:
    name: github-token
  type: github

