---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  channel: delivery-k8s-maksystem
  secretRef:
    name: slack-url
  type: slack

